events {}

http {
    upstream frontend_backend {
        server frontend:3000;
    }

    upstream campaign_backend {
        server campaign-service:8001;
    }

    upstream stratification_backend {
        server stratification-service:8002;
    }

    upstream communication_backend {
        server communication-service:8003;
    }

    upstream engagement_backend {
        server engagement-service:8004;
    }

    upstream analytics_backend {
        server analytics-service:8005;
    }

    server {
        listen 8000;
        server_name localhost;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        location /api/campaigns/ {
            proxy_pass http://campaign_backend/;
        }

        location /api/stratify/ {
            proxy_pass http://stratification_backend/;
        }

        location /api/communication/ {
            proxy_pass http://communication_backend/;
        }

        location /api/engagement/ {
            proxy_pass http://engagement_backend/;
        }

        location /api/analytics/ {
            proxy_pass http://analytics_backend/;
        }

        location / {
            proxy_pass http://frontend_backend;
        }
    }
}
